import type { Metadata } from 'next'
import { Geist, Geist_Mono, Satisfy } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const satisfy = Satisfy({
  subsets: ['latin'],
  weight: '400', // optional
  variable: '--font-satisfy', // optional CSS variable
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${satisfy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
